package com.main

import com.app.rwm.model.Injury;
import com.app.rwm.model.TrainingPlan;
import com.app.rwm.enums.INJURY_TYPE;

rule "Injury severe"
	agenda-group "injury"
	when 
		$i : Injury(injuryType == INJURY_TYPE.BROKEN_LEG, injuryCategory == InjuryCategory.NA )
    then
    	System.out.println("SEVERE_INJURY and cancel preparation");
        $i.setInjuryCategory(Injury.InjuryCategory.SEVERE_INJURY);
        update($i);
end

// uraditi kategoriju p2 za vise od dvije povrede tipa p1 - accumulate

rule "Cancel preparation if severe injury"
	agenda-group "injury"
	when
		$i: Injury(injuryCategory == InjuryCategory.SEVERE_INJURY)
		$p: TrainingPlan()
	then
		System.out.println("Cancel the preparation");
		modify($p){setCanceledPreparation(true);}
end
// Uraditi Cancel preparation za jos 6 tacaka

rule "Injury minor"
	agenda-group "injury"
	when 
		$i : Injury(injuryType == INJURY_TYPE.KNEE_PAIN || injuryType == INJURY_TYPE.ACHILLES_TENDINITIS, injuryCategory == InjuryCategory.NA )
    then
    	System.out.println("Normal");
        $i.setInjuryCategory(Injury.InjuryCategory.MINOR_INJURY);
        update($i);
end



