package com.main

import java.time.Instant;
import java.time.temporal.ChronoUnit;

import com.app.rwm.model.TrainingPlan;
import com.app.rwm.model.RunnerData;
import com.app.rwm.enums.PREPARATION_TIME;
import com.app.rwm.enums.INTENSITY;

rule "novice00"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.STARTER, preparationTime == PREPARATION_TIME.WEEK_8_TO_12)
	then
		System.out.println("novice00");
		modify($t){setTrainingName("novice00");}
end

rule "novice01"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.STARTER, preparationTime == PREPARATION_TIME.WEEK_13_TO_16)
	then
		System.out.println("novice01");
		modify($t){setTrainingName("novice01");}
end

rule "novice02"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.STARTER, preparationTime == PREPARATION_TIME.WEEK_17_TO_24)
	then
		System.out.println("novice02");
		modify($t){setTrainingName("novice02");}
end

rule "novice20"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.ADVANCED, preparationTime == PREPARATION_TIME.WEEK_8_TO_12)
	then
		System.out.println("novice20");
		modify($t){setTrainingName("novice20");}
end

rule "novice21"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.ADVANCED, preparationTime == PREPARATION_TIME.WEEK_13_TO_16)
	then
		System.out.println("novice21");
		modify($t){setTrainingName("novice21");}
end

rule "novice22"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.ADVANCED, preparationTime == PREPARATION_TIME.WEEK_17_TO_24)
	then
		System.out.println("novice22");
		modify($t){setTrainingName("novice22");}
end

rule "nan"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == null)
	then
		System.out.println("nan");
		modify($t){setTrainingName("nan"),setCanceledPreparation(true);}
end