package com.main

import java.time.Instant;
import java.time.temporal.ChronoUnit;

import com.app.rwm.model.TrainingPlan;
import com.app.rwm.model.RunnerData;
import com.app.rwm.enums.PREPARATION_TIME;
import com.app.rwm.enums.INTENSITY;

rule "STARTER_WEEK_8_TO_12"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.STARTER || intensityLevel == null , preparationTime == PREPARATION_TIME.WEEK_8_TO_12)
	then
		System.out.println("STARTER_WEEK_8_TO_12");
		modify($t){setTrainingName("STARTER_WEEK_8_TO_12");}
end

rule "STARTER_WEEK_13_TO_16"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.STARTER || intensityLevel == null , preparationTime == PREPARATION_TIME.WEEK_13_TO_16)
	then
		System.out.println("STARTER_WEEK_13_TO_16");
		modify($t){setTrainingName("STARTER_WEEK_13_TO_16");}
end

rule "STARTER_WEEK_17_TO_24"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.STARTER || intensityLevel == null , preparationTime == PREPARATION_TIME.WEEK_17_TO_24)
	then
		System.out.println("STARTER_WEEK_17_TO_24");
		modify($t){setTrainingName("STARTER_WEEK_17_TO_24");}
end

rule "ADVANCED_WEEK_8_TO_12"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.ADVANCED, preparationTime == PREPARATION_TIME.WEEK_8_TO_12)
	then
		System.out.println("ADVANCED_WEEK_8_TO_12");
		modify($t){setTrainingName("ADVANCED_WEEK_8_TO_12");}
end

rule "ADVANCED_WEEK_13_TO_16"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.ADVANCED, preparationTime == PREPARATION_TIME.WEEK_13_TO_16)
	then
		System.out.println("ADVANCED_WEEK_13_TO_16");
		modify($t){setTrainingName("ADVANCED_WEEK_13_TO_16");}
end

rule "ADVANCED_WEEK_17_TO_24"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == INTENSITY.ADVANCED , preparationTime == PREPARATION_TIME.WEEK_17_TO_24)
	then
		System.out.println("ADVANCED_WEEK_17_TO_24");
		modify($t){setTrainingName("ADVANCED_WEEK_17_TO_24");}
end

rule "nan"
	agenda-group "plan"
	lock-on-active
	when 
		$t : TrainingPlan(intensityLevel == null )
	then
		System.out.println("nan");
		modify($t){setTrainingName("nan"),setCanceledPreparation(true);}
end